#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["WeatherOrNot/WeatherOrNot.csproj", "WeatherOrNot/"]
COPY ["WeatherOrNot.Logic/WeatherOrNot.Logic.csproj", "WeatherOrNot.Logic/"]
RUN dotnet restore "WeatherOrNot/WeatherOrNot.csproj"
RUN dotnet restore "WeatherOrNot.Logic/WeatherOrNot.Logic.csproj"
COPY . .
WORKDIR "/src/WeatherOrNot"
RUN dotnet publish "WeatherOrNot.csproj" -c Release -o publish

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS final
EXPOSE 80
EXPOSE 443
WORKDIR /app
COPY --from=build /src/publish .
ENTRYPOINT ["dotnet", "WeatherOrNot.dll"]